fix to GHA

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -4,38 +4,41 @@ on:
     branches:
       - main
 jobs:
-  eslint:
+  tests:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        commands: ['lint', 'test', 'coverage', 'build']
+    name: ${{ matrix.commands }}
+    env:
+      PORT: 3333
+      HOST: 0.0.0.0
+      NODE_ENV: development
+      APP_KEY: TU0ek-AcW9NoEi3Sy0m4B0vuGq_9xVOT
+      DRIVE_DISK: local
     steps:
       - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
       - uses: actions/setup-node@v2
         with:
           node-version: 16
-      - run: npm ci
-      - uses: sibiraj-s/action-eslint@v2
-        with:
-          eslint-args: '--ignore-path=.gitignore --quiet'
-          extensions: 'js,jsx,ts,tsx'
-          annotations: true  
-  test:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v2
-        with:
-          node-version: 16
-      - run: |
-          cp .env.example .env
-          npm ci
-          npm test
-          npm run coverage
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v2
-        with:
-          node-version: 16
-      - run:
-          npm ci
-          npm build
+
+      - name: Install Deps
+        run: npm ci
+        
+      - name: Run ${{ matrix.commands }}
+        run: |
+          if [[ "${{ matrix.commands }}" == "lint" ]]; then
+            npm run lint
+          elif [[ "${{ matrix.commands }}" == "test" ]]; then
+            npm run test
+          elif [[ "${{ matrix.commands }}" == "coverage" ]]; then
+            npm run test
+          elif [[ "${{ matrix.commands }}" == "build" ]]; then            
+            npm run build
+          else
+            echo "Invalid command"
+            exit 1
+          fi
